[homepage]
background_color = "000000"
background_image_landscape = "niciuna.jpg"

[homepage*l]
background_color = "ffffff"

[homepage.tq]
image = "imagine"
name = "nume"

[homepage.eq*l]
image = "imagine_landscape"

[homepage.tq*l]
name = "nume_landscape"

[@orice_element]
name = "1"

[@orice_element*andpadl]
name = "prrrreeea"

[alt_view]
tesst = "test"