[app]
web_path = "http://razvan.freshweb.ro/ignitephp/"
assets_path = "assets/"
static_xml_path = "static/"

[monolog]
logfile = "development.log"

[memcache]
type = "elastic"
enabled = "false"
host = "dolphin-api-micro.eat5yi.cfg.euw1.cache.amazonaws.com"
port = 11211
expiration = 3600