[app]
#as assigned in appscend interface including the trailing slash
dispatch_url = "http://example.com/"
assets_path = "assets/"
static_xml_path = "static/"
devel_env = false

[gelf]
domain = "example.net"
port = 12201
facility = "ignitephp_dev"

[memcache]
type = "elastic"
enabled = "false"
host = "example.com"
port = 11211
expiration = 3600