[app]
assets_path = "assets/"
static_xml_path = "static/"

[gelf]
domain = "example.net"
port = 12201
facility = "ignitephp_dev"

[memcache]
type = "elastic"
enabled = "false"
host = "example.com"
port = 11211
expiration = 3600